name: My-Githab-action
on:
  push:
    branches:
      -master
jobs:
  Build_ubuntu_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        run: actions/checkout@v3
      - name: Multiple comands
        run: |
          ls -la
          zip -version
          echo " Hello!"
      - name: Print my text
        run: echo "Test is done!"
        #needs: [Build_ubuntu_tests] - Šis ir lai palaiztos nākamais dokeris, figūriekavās norādam iepriekēšā
