name: My-Githab-action
on:  
  push:
    branches-ignore:
     - master
jobs:
  build_my_test:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone
        run: actions/checkout@v3
        
      - name: Multiple comands
        run: |
          ls -la
          zip -version
          echo " Hello!"
          
      - name: Check pyton version
        run: pyton3 -version
        
        #needs: [build_my_test] - Šis ir lai palaiztos nākamais dokeris, figūriekavās norādam iepriekēšā.
